"""users table

Revision ID: 5ee5f3d86966
Revises: 
Create Date: 2023-12-16 17:34:16.283981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ee5f3d86966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('applications')
  op.drop_table('jobs')
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
      'applications',
      sa.Column('id',
                sa.INTEGER(),
                sa.Identity(always=True,
                            start=1,
                            increment=1,
                            minvalue=1,
                            maxvalue=2147483647,
                            cycle=False,
                            cache=1),
                autoincrement=True,
                nullable=False),
      sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
      sa.Column('fullname',
                sa.VARCHAR(length=250),
                autoincrement=False,
                nullable=True),
      sa.Column('email',
                sa.VARCHAR(length=250),
                autoincrement=False,
                nullable=True),
      sa.Column('linkedin',
                sa.VARCHAR(length=250),
                autoincrement=False,
                nullable=True),
      sa.Column('education',
                sa.VARCHAR(length=2000),
                autoincrement=False,
                nullable=True),
      sa.Column('workexperience',
                sa.VARCHAR(length=2000),
                autoincrement=False,
                nullable=True),
      sa.Column('resumelink',
                sa.VARCHAR(length=500),
                autoincrement=False,
                nullable=True),
      sa.Column('created_at',
                postgresql.TIMESTAMP(),
                server_default=sa.text('CURRENT_TIMESTAMP'),
                autoincrement=False,
                nullable=True),
      sa.PrimaryKeyConstraint('id', name='applications_pkey'))
  op.create_table(
      'jobs',
      sa.Column('id',
                sa.INTEGER(),
                sa.Identity(always=True,
                            start=1,
                            increment=1,
                            minvalue=1,
                            maxvalue=2147483647,
                            cycle=False,
                            cache=1),
                autoincrement=True,
                nullable=False),
      sa.Column('title',
                sa.VARCHAR(length=120),
                autoincrement=False,
                nullable=False),
      sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True),
      sa.Column('currency',
                sa.VARCHAR(length=10),
                autoincrement=False,
                nullable=True),
      sa.Column('responsibilities',
                sa.VARCHAR(length=2000),
                autoincrement=False,
                nullable=True),
      sa.Column('requirements',
                sa.VARCHAR(length=2000),
                autoincrement=False,
                nullable=True),
      sa.Column('created_at',
                postgresql.TIMESTAMP(),
                server_default=sa.text('CURRENT_TIMESTAMP'),
                autoincrement=False,
                nullable=True),
      sa.Column('updated_at',
                postgresql.TIMESTAMP(),
                server_default=sa.text('CURRENT_TIMESTAMP'),
                autoincrement=False,
                nullable=True),
      sa.Column('location',
                sa.VARCHAR(length=200),
                autoincrement=False,
                nullable=True), sa.PrimaryKeyConstraint('id',
                                                        name='jobs_pkey'))
  # ### end Alembic commands ###
